name: Deploy

on: [pull_request]

concurrency: '1'

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          set +x
          git config user.name ${{env.GITHUB_ACTOR}}
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          if ! git fetch origin storybook-static ; then echo "Create storybook-static branch" fi
