name: Deploy

on: [pull_request]

concurrency: '1'

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $GITHUB_ACTOR
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          # git fetch origin storybook-static || true
          TEMP_DIR=$(mktemp -d)
          CURRENT_BRANCH=$(git branch)
          if ! git fetch origin storybook-static; then
            echo "Create storybook-static branch"
            git checkout --orphan storybook-static
            git rm --cached -r .
            git commit -am "Init"
            git push
            git checkout $CURRENT_BRANCH
          fi

          echo "Hello done"
